echo "ENTER YOUR NAME:"
read $USER_NAME
echo "ENTER YOUR AGE:"
read $USER_AGE
echo "ENTER YOUR FAVORITE PROGRAMMING LANGUAGE:"
read $USER_LANGUAGE

echo "THANK YOU $USER_NAME, YOUR ARE $USER_AGE YEARS OLD & YOUR FAVORITE PROGRAMMING LANGUAGE IS $USER_LANGUAGE"
